name: Tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install homeassistant pytest pytest-homeassistant-custom-component ruff
      - run: ruff check . --fix
      - run: pytest -q
